server:
  port: 8084
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/northwind}
    username: ${DB_USER:northwind}
    password: ${DB_PASSWORD:northwind}
  jpa:
    hibernate:
      ddl-auto: none
clients:
  inventory-url: ${INVENTORY_URL:http://localhost:8085}
  billing-url: ${BILLING_URL:http://localhost:8086}
  warehouse-url: ${WAREHOUSE_URL:http://localhost:8087}
