server:
  port: 8085
spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/northwind}
    username: ${DB_USER:northwind}
    password: ${DB_PASSWORD:northwind}
  jpa:
    hibernate:
      ddl-auto: none
